'use client';
import {Fragment,useEffect,useRef,useState} from 'react';
import {Search,Shuffle,Archive,BookOpen,Camera,Newspaper,Headphones,Box,ExternalLink,X,SlidersHorizontal,LoaderCircle} from 'lucide-react';
import ArchiveViewer,{actionLabel} from '../components/archive-viewer';
import {yearHeading} from '../lib/chronology';
import PlacePicker from '../components/place-picker';
import {resolvePlace} from '../lib/place-filter';
import PeriodPicker from '../components/period-picker';
import {periodLabel} from '../lib/period';
import useArchiveResults from '../hooks/use-archive-results';
import type {RecordItem} from '../lib/archive';
const sources:Record<string,string>={nb:'Nasjonalbiblioteket',ia:'Internet Archive',dm:'DigitaltMuseum'};
const kinds=[['all','Alle skuffer',Archive],['photos','Bilder',Camera],['objects','Gjenstander',Box],['news','Aviser',Newspaper],['books','Bøker',BookOpen],['audio','Lyd',Headphones]] as const;
const drawers=[{q:'Bergen',year:'1900',label:'Byliv i Bergen',note:'Gater, mennesker og hverdag',kind:'all'},{q:'jernbane',year:'1920',label:'Norge på skinner',note:'Reiser i en annen tid',kind:'all'},{q:'polar',year:'1911',label:'Mot det ukjente',note:'På sporet av polfarerne',kind:'books'},{q:'folkemusikk',year:'',label:'Stemmer fra før',note:'Musikk og gamle opptak',kind:'audio'},{q:'Kristiania',year:'1890',label:'Før byen het Oslo',note:'Et glimt av Kristiania',kind:'photos'},{q:'fiske',year:'1930',label:'Livet langs kysten',note:'Arbeid, hav og hjem',kind:'all'}];
const iconFor=(k:string)=>k==='Bilder'?Camera:k==='Aviser'?Newspaper:k==='Lyd'?Headphones:k==='Gjenstander'?Box:BookOpen;
export default function Home(){
 const [query,setQuery]=useState('Bergen'),[year,setYear]=useState('1900'),[kind,setKind]=useState('all'),[source,setSource]=useState('all'),[order,setOrder]=useState('oldest'),[access,setAccess]=useState('available'),[catalog,setCatalog]=useState(false);
 const [search,setSearch]=useState({q:'Bergen',year:'1900',kind:'all',source:'all',access:'available',catalog:false,order:'oldest',place:'',page:0,nonce:0});
 const {data,items,loading,loadingMore,error,loadMore,hasMore,cancelMore}=useArchiveResults(search);
 const [selected,setSelected]=useState<RecordItem|null>(null),[about,setAbout]=useState(false),[galleryPending,setGalleryPending]=useState(false),[viewerPeriodOpen,setViewerPeriodOpen]=useState(false);
 const aboutDialog=useRef<HTMLDialogElement>(null),pendingDialog=useRef<HTMLDialogElement>(null),galleryRequest=useRef(0);
 const changePeriod=(value:string)=>{setYear(value);setSearch(s=>({...s,year:value,page:0,nonce:Date.now()}));if(selected){setViewerPeriodOpen(true);setGalleryPending(true);setSelected(null)}galleryRequest.current++};
 useEffect(()=>{if(galleryPending)pendingDialog.current?.showModal()},[galleryPending]);
 useEffect(()=>{if(galleryPending&&!loading){const first=items.find(i=>i.kind==='Bilder');if(first){setSelected(first);setGalleryPending(false)}}},[galleryPending,loading,items]);
 const closeGallery=()=>{cancelMore();galleryRequest.current++;setSelected(null);setGalleryPending(false)};
 const nextPhoto=async()=>{if(loadingMore)return;if(photoIndex<photos.length-1){setSelected(photos[photoIndex+1]);return}const request=++galleryRequest.current;const next=await loadMore(true);if(next&&request===galleryRequest.current)setSelected(next)};
 useEffect(()=>{if(about)aboutDialog.current?.showModal();else aboutDialog.current?.close()},[about]);
 const run=(k=kind,s=source,a=access,c=catalog)=>setSearch({q:query.trim(),year,kind:k,source:s,access:a,catalog:c,order,place:search.place,page:0,nonce:Date.now()});
 const openDrawer=(d:typeof drawers[number])=>{setQuery(d.q);setYear(d.year);setKind(d.kind);setSource('all');setAccess('available');setCatalog(false);setSearch({q:d.q,year:d.year,kind:d.kind,source:'all',access:'available',catalog:false,order,place:'',page:0,nonce:Date.now()})};
 const random=()=>{const choices=drawers.filter(d=>d.q!==search.q);openDrawer(choices[Math.floor(Math.random()*choices.length)])};
 const shown=items,total=data.reduce((n,s)=>n+(s.total||0),0);
 const photos=shown.filter(item=>item.kind==='Bilder'),photoIndex=selected?photos.findIndex(item=>item.source===selected.source&&item.id===selected.id):-1;
 const text=[search.q,search.place?resolvePlace(search.place)?.label:'',search.year?periodLabel(search.year):''].filter((v,i,a)=>v&&a.findIndex(x=>x?.toLocaleLowerCase()===v.toLocaleLowerCase())===i).join(' · ');
 const links=[{id:'nb',href:'https://www.nb.no/search?q='+encodeURIComponent([search.q,search.place?resolvePlace(search.place)?.label:'',search.year].filter(Boolean).join(' '))},{id:'dm',href:'https://digitaltmuseum.no/search/?q='+encodeURIComponent([search.q,search.place?resolvePlace(search.place)?.label:'',search.year].filter(Boolean).join(' '))},{id:'ia',href:'https://archive.org/search?query='+encodeURIComponent([search.q,search.place?resolvePlace(search.place)?.label:'',search.year?'year:'+search.year:''].filter(Boolean).join(' '))}];
 return <><header className="top"><a href="/" className="brand"><Archive size={25}/><span>Historieloftet<span className="brand-small">ET STED FOR GAMLE SPOR</span></span></a><button className="text-button" onClick={()=>setAbout(true)}>Om kildene <ExternalLink size={15}/></button></header><main>
 <section className="intro"><div><div className="eyebrow">TRE ARKIVER. UTALLIGE HISTORIER.</div><h1>Hva vil du finne <em>igjen?</em></h1><p>Et sted, et årstall, en liten nysgjerrighet. Åpne en skuff i historien.</p></div><button className="random" onClick={random}><Shuffle size={19}/> Åpne en tilfeldig skuff</button></section>
 <div className="catalog-shell"><section className="search-panel" aria-label="Søk i arkivene"><form onSubmit={e=>{e.preventDefault();run()}}><label className="query"><span>STED ELLER TEMA</span><div><Search size={22}/><input aria-label="Sted eller tema" placeholder="Bergen, fiske eller polar" value={query} onChange={e=>setQuery(e.target.value)} maxLength={150}/></div></label><div className="year"><span>TIDSPERIODE</span><button type="button" className="period-trigger" onClick={()=>{const panel=document.getElementById('search-period-panel');panel?.scrollIntoView({behavior:'smooth',block:'nearest'});panel?.focus({preventScroll:true})}} aria-controls="search-period-panel">{periodLabel(year)} ▾</button></div><button className="search-button" type="submit">Let i historien <Search size={18}/></button></form><nav className="tabs" aria-label="Materialtype">{kinds.map(([id,label,Icon])=><button key={id} className={kind===id?'active':''} aria-pressed={kind===id} onClick={()=>{setKind(id);run(id)}}><Icon size={18}/>{label}</button>)}</nav></section>
 <div className="workspace"><aside><div className="eyebrow side-title"><SlidersHorizontal size={15}/> AVGRENS SØKET</div><label className="select-label">Kilde<select value={source} onChange={e=>{setSource(e.target.value);run(kind,e.target.value)}}><option value="all">Alle tre arkiver</option>{Object.entries(sources).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label className="select-label">Tilgang<select value={access} onChange={e=>{const a=e.target.value;setAccess(a);if(a!=='all')setCatalog(false);run(kind,source,a,a==='all'?catalog:false)}}><option value="available">På nett – åpent / fra Norge</option><option value="open">Fritt tilgjengelig</option><option value="norway">Tilgjengelig fra Norge</option><option value="restricted">Krever særskilt tilgang</option><option value="offline">Ikke digitalisert</option><option value="all">Alle tilganger</option></select></label><label className="catalog-toggle"><input type="checkbox" checked={catalog||access==='offline'} disabled={access==='offline'} onChange={e=>{const c=e.target.checked;setCatalog(c);if(c)setAccess('all');run(kind,source,c?'all':access,c)}}/> Ta med rene katalogposter</label><p className="small">Filtrene brukes i kildesøkene før treffene hentes. «Fra Norge» søker i NBs Bokhylla-materiale.</p><div className="side-rule"/><div className="eyebrow">EN ANNEN SKUFF</div><div className="drawers">{drawers.slice(1,5).map((d,i)=><button key={d.q} onClick={()=>openDrawer(d)}><span className="drawer-number">0{i+1}</span><span><b>{d.label}</b><small>{d.year||'Ulike år'} · {d.note}</small></span></button>)}</div></aside>
 <section className="results" aria-label="Søkeresultater"><div className="results-head"><label className="sort-control">Sorter etter<select aria-label="Sorter etter" value={order} onChange={e=>{setOrder(e.target.value);setSearch(s=>({...s,order:e.target.value,nonce:Date.now()}));closeGallery()}}><option value="oldest">Eldste først</option><option value="newest">Nyeste først</option></select></label><div className="eyebrow">PÅ ARKIVBORDET</div><h2>{text||'Ditt neste funn'}</h2><p aria-live="polite">{loading?'Leter etter spor i arkivene …':`${shown.length} viste funn${total?' · '+total.toLocaleString('nb-NO')+' katalogtreff':''}`}</p></div>
 {(source==='all'||source==='dm')&&<div className="source-note"><Box size={20}/><div><b>En skuff til hos DigitaltMuseum</b><span>{data.find(s=>s.source==='dm')?.error||data.find(s=>s.source==='dm')?.notice||'Museumsgjenstander og fotografier i originalkatalogen.'}</span></div><a href={links[1].href} target="_blank" rel="noreferrer">Søk hos museene <ExternalLink size={14}/></a></div>}
 {!loading&&data.filter(s=>s.error&&s.source!=='dm').map(s=><div className="notice" key={s.source} role="status">{s.error} <a href={links.find(l=>l.id===s.source)?.href} target="_blank" rel="noreferrer">Åpne kildesøk</a></div>)}{!loading&&data.filter(s=>s.notice&&s.source!=='dm').map(s=><p className="filter-note" key={s.source}>{s.notice}</p>)}{error&&<div className="notice" role="alert">{error} <button onClick={()=>items.length?void loadMore():run()}>Prøv igjen</button></div>}
 {loading?<div className="loading"><LoaderCircle className="spin"/><p>Vi trekker ut skuffene …</p></div>:<><div className="cards">{shown.map((item,index)=>{const Icon=iconFor(item.kind);return <Fragment key={item.source+item.id}>{(index===0||yearHeading(shown[index-1])!==yearHeading(item))&&<h3 className="year-heading">{yearHeading(item)}</h3>}<button className="card" onClick={()=>setSelected(item)}><div className={'card-visual '+(item.kind==='Lyd'?'sound':item.kind==='Aviser'?'news':'')}><span className="catalog-label">{item.source.toUpperCase()} / {String(search.page*24+index+1).padStart(3,'0')}</span>{item.image?<img src={item.image} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/>:<div className="type-display"><Icon size={43} strokeWidth={1}/><span>{item.kind}</span></div>}<span className="date-label">{item.year||'Udatert'}</span></div><div className="card-body"><div className="card-source">{sources[item.source]}</div><h3>{item.title}</h3><p className="creator">{item.creator||item.description||'Utforsk originalposten'}</p><span className={'access '+(item.open?'available':'')}>{item.access}</span><span className="card-action">{actionLabel(item)} <ExternalLink size={14}/></span></div></button></Fragment>})}</div>{!shown.length&&<div className="empty"><Archive size={35}/><h3>{kind==='objects'?'Gjenstandene finner du hos museene':'Ingen funn i denne skuffen'}</h3><p>{kind==='objects'?'Åpne DigitaltMuseum med søket ditt. Direkte museumssøk trenger API-tilgang.':'Prøv et annet søkeord, fjern årstallet eller velg en annen tilgang.'}</p><div className="source-links">{links.filter(l=>source==='all'||l.id===source).map(l=><a key={l.id} href={l.href} target="_blank" rel="noreferrer">Søk hos {sources[l.id]} <ExternalLink size={14}/></a>)}</div></div>}{hasMore&&<div className="pagination"><button disabled={loadingMore} onClick={()=>void loadMore()}>{loadingMore?'Henter flere treff …':error?'Prøv å hente flere igjen':'Last inn flere treff'}</button><span>{items.length} lastet inn</span></div>}</>}
 </section></div><section id="search-period-panel" className="period-rail" tabIndex={-1} aria-label="Filtrer på tidsperiode"><PeriodPicker value={search.year} onChange={changePeriod}/><PlacePicker value={search.place} onChange={place=>{setSearch(s=>({...s,place,nonce:Date.now()}));closeGallery()}}/></section></div><footer><span>Historieloftet <span className="muted">/ Fortiden er nærmere enn du tror.</span></span><button onClick={()=>setAbout(true)}>Kilder, tilgang og rettigheter</button></footer></main>
 {selected&&<ArchiveViewer key={selected.source+selected.id} item={selected} photoIndex={photoIndex} photoCount={photos.length} morePhotos={hasMore} fetchingPhotos={loadingMore} galleryError={error} periodExpanded={viewerPeriodOpen} period={search.year} onPeriodChange={changePeriod} onPrevious={photoIndex>0&&!loadingMore?()=>setSelected(photos[photoIndex-1]):undefined} onNext={photoIndex>=0&&(photoIndex<photos.length-1||hasMore)?()=>void nextPhoto():undefined} onClose={closeGallery}/>}
 {galleryPending&&<dialog ref={pendingDialog} className="period-wait-dialog" onCancel={closeGallery} onClose={closeGallery}><button onClick={closeGallery} aria-label="Lukk visningen">Lukk</button><h2>{loading?'Henter bilder …':'Ingen bilder i valgt periode'}</h2><p>{error||'Søkeord og øvrige filtre beholdes.'}</p><PeriodPicker value={search.year} onChange={changePeriod}/></dialog>}
 <dialog aria-label="Kilder og rettigheter" ref={aboutDialog} onClose={()=>setAbout(false)}><div className="dialog-content"><button className="close" onClick={()=>setAbout(false)} aria-label="Lukk kildeinformasjon"><X/></button><div className="eyebrow">OM LOFTET</div><h2>Tre dører til fortiden.</h2><p>Historieloftet søker i originalkataloger. Søkeord behandles som fritekst, og årstall som et eget filter. Et årstall kan beskrive utgivelse eller katalogens datering, ikke nødvendigvis motivet.</p><h3>Nasjonalbiblioteket</h3><p>Bøker, aviser, bilder og musikk. «Fritt tilgjengelig» krever at katalogen oppgir digitalt materiale, full visning og tilgang overalt. Andre funn kan kreve norsk IP-adresse, innlogging eller bibliotekbesøk.</p><a href="https://www.nb.no/tilgang/rettigheter/" target="_blank" rel="noreferrer">Les om Nasjonalbibliotekets tilgang</a><h3>DigitaltMuseum</h3><p>Museumsgjenstander og fotografier. Åpnes med søkeord og årstall hos DigitaltMuseum inntil egen API-nøkkel er satt opp. Årstallet i denne søkelenken er fritekst.</p><a href="https://store-search.dimu.org/docs" target="_blank" rel="noreferrer">DigitaltMuseums dokumentasjon</a><h3>Internet Archive</h3><p>Bøker, bilder og lyd. Tilgang sjekkes når du åpner et funn; enkelte bøker krever lån. Lyd spilles her når kilden oppgir en åpen lisens og en tilgjengelig MP3-fil. Åpne, skannede bøker kan leses i Internet Archives innebygde leser.</p><a href="https://archive.org/developers/" target="_blank" rel="noreferrer">Internet Archives dokumentasjon</a><h3>Et funn er ikke en gjenbrukstillatelse</h3><p>Bilder, bøker og aviser fra Nasjonalbiblioteket kan vises stort og blaes i her når kilden oppgir fri nettilgang og public domain eller en støttet Creative Commons-lisens. CC BY-NC-materiale vises for ikke-kommersiell bruk, med kreditering og lenke til lisensen. Bokhylla-materiale åpnes i NBs leser. Rettigheter og tilgang kan endres.</p><p className="small">Treff blandes fra de tilkoblede kildene. Tilgangsfiltrene gjelder hele søket i kildekatalogen. NB bruker tilgangsgruppene public, bokhylla og restricted. Internet Archive filtreres etter lånemerking, og filtilgang sjekkes ved åpning. Internet Archive har ingen tilsvarende Norge- eller ikke-digitalisert-kategori. DigitaltMuseum åpnes hos kilden og inngår ikke i tilgangsfiltrerte treff. Aviser søkes i Nasjonalbiblioteket, gjenstander hos DigitaltMuseum. Tilfeldig skuff velger mellom seks søkespor.</p></div></dialog></>;
}


