'use client';
import {useEffect,useRef,useState} from 'react';
import {Search,Shuffle,Archive,BookOpen,Camera,Newspaper,Headphones,Box,ExternalLink,X,SlidersHorizontal,LoaderCircle} from 'lucide-react';
import type {RecordItem} from '../lib/archive';
const sources:Record<string,string>={nb:'Nasjonalbiblioteket',ia:'Internet Archive',dm:'DigitaltMuseum'};
const kinds=[['all','Alle skuffer',Archive],['photos','Bilder',Camera],['objects','Gjenstander',Box],['news','Aviser',Newspaper],['books','Bøker',BookOpen],['audio','Lyd',Headphones]] as const;
const drawers=[{q:'Bergen',year:'1900',label:'Byliv i Bergen',note:'Gater, mennesker og hverdag',kind:'all'},{q:'jernbane',year:'1920',label:'Norge på skinner',note:'Reiser i en annen tid',kind:'all'},{q:'polar',year:'1911',label:'Mot det ukjente',note:'På sporet av polfarerne',kind:'books'},{q:'folkemusikk',year:'',label:'Stemmer fra før',note:'Musikk og gamle opptak',kind:'audio'},{q:'Kristiania',year:'1890',label:'Før byen het Oslo',note:'Et glimt av Kristiania',kind:'photos'},{q:'fiske',year:'1930',label:'Livet langs kysten',note:'Arbeid, hav og hjem',kind:'all'}];
const iconFor=(k:string)=>k==='Bilder'?Camera:k==='Aviser'?Newspaper:k==='Lyd'?Headphones:k==='Gjenstander'?Box:BookOpen;
export default function Home(){
 const [query,setQuery]=useState('Bergen'),[year,setYear]=useState('1900'),[kind,setKind]=useState('all'),[source,setSource]=useState('all'),[access,setAccess]=useState('all');
 const [search,setSearch]=useState({q:'Bergen',year:'1900',kind:'all',source:'all',page:0,nonce:0});
 const [data,setData]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<RecordItem|null>(null),[detail,setDetail]=useState<any>(null),[checking,setChecking]=useState(false),[about,setAbout]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),aboutDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const c=new AbortController();setLoading(true);setError('');fetch('/api/search?'+new URLSearchParams(Object.entries(search).map(([k,v])=>[k,String(v)])),{signal:c.signal}).then(r=>r.json()).then((d:any)=>{if(d.error)throw Error(d.error);setData(d.sources||[])}).catch(e=>{if(e.name!=='AbortError'){setError(e.message||'Søket kunne ikke lastes.');setData([])}}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[search]);
 useEffect(()=>{if(!selected){dialog.current?.close();return}dialog.current?.showModal();setDetail(null);setChecking(selected.source==='ia');if(selected.source==='ia'){const c=new AbortController();fetch('/api/access?id='+encodeURIComponent(selected.id),{signal:c.signal}).then(r=>r.json()).then(setDetail).catch(e=>{if(e.name!=='AbortError')setDetail({error:'Tilgangen kunne ikke sjekkes.'})}).finally(()=>{if(!c.signal.aborted)setChecking(false)});return()=>c.abort()}},[selected]);
 useEffect(()=>{if(about)aboutDialog.current?.showModal();else aboutDialog.current?.close()},[about]);
 const run=(k=kind,s=source)=>setSearch({q:query.trim(),year,kind:k,source:s,page:0,nonce:Date.now()});
 const openDrawer=(d:typeof drawers[number])=>{setQuery(d.q);setYear(d.year);setKind(d.kind);setSource('all');setAccess('all');setSearch({q:d.q,year:d.year,kind:d.kind,source:'all',page:0,nonce:Date.now()})};
 const random=()=>{const choices=drawers.filter(d=>d.q!==search.q);openDrawer(choices[Math.floor(Math.random()*choices.length)])};
 const items:RecordItem[]=Array.from({length:12},(_,i)=>data.map(s=>s.items?.[i]).filter(Boolean)).flat(),shown=items.filter(i=>access==='all'||i.open),total=data.reduce((n,s)=>n+(s.total||0),0);
 const text=[search.q,search.year].filter(Boolean).join(' · ');
 const links=[{id:'nb',href:'https://www.nb.no/search?q='+encodeURIComponent([search.q,search.year].filter(Boolean).join(' '))},{id:'dm',href:'https://digitaltmuseum.no/search/?q='+encodeURIComponent([search.q,search.year].filter(Boolean).join(' '))},{id:'ia',href:'https://archive.org/search?query='+encodeURIComponent([search.q,search.year?'year:'+search.year:''].filter(Boolean).join(' '))}];
 return <><header className="top"><a href="/" className="brand"><Archive size={25}/><span>Historieloftet<span className="brand-small">ET STED FOR GAMLE SPOR</span></span></a><button className="text-button" onClick={()=>setAbout(true)}>Om kildene <ExternalLink size={15}/></button></header><main>
 <section className="intro"><div><div className="eyebrow">TRE ARKIVER. UTALLIGE HISTORIER.</div><h1>Hva vil du finne <em>igjen?</em></h1><p>Et sted, et årstall, en liten nysgjerrighet. Åpne en skuff i historien.</p></div><button className="random" onClick={random}><Shuffle size={19}/> Åpne en tilfeldig skuff</button></section>
 <section className="search-panel" aria-label="Søk i arkivene"><form onSubmit={e=>{e.preventDefault();run()}}><label className="query"><span>STED ELLER TEMA</span><div><Search size={22}/><input aria-label="Sted eller tema" placeholder="Bergen, fiske eller polar" value={query} onChange={e=>setQuery(e.target.value)} maxLength={150}/></div></label><label className="year"><span>ÅRSTALL</span><input aria-label="Årstall" inputMode="numeric" pattern="[0-9]{4}" placeholder="Alle år" value={year} onChange={e=>setYear(e.target.value)} maxLength={4}/></label><button className="search-button" type="submit">Let i historien <Search size={18}/></button></form><nav className="tabs" aria-label="Materialtype">{kinds.map(([id,label,Icon])=><button key={id} className={kind===id?'active':''} aria-pressed={kind===id} onClick={()=>{setKind(id);run(id)}}><Icon size={18}/>{label}</button>)}</nav></section>
 <div className="workspace"><aside><div className="eyebrow side-title"><SlidersHorizontal size={15}/> AVGRENS SØKET</div><label className="select-label">Kilde<select value={source} onChange={e=>{setSource(e.target.value);run(kind,e.target.value)}}><option value="all">Alle tre arkiver</option>{Object.entries(sources).map(([id,name])=><option value={id} key={id}>{name}</option>)}</select></label><label className="select-label">Tilgang i viste treff<select value={access} onChange={e=>setAccess(e.target.value)}><option value="all">Alle katalogfunn</option><option value="open">Bekreftet fri nettilgang</option></select></label><p className="small">Et katalogfunn er et spor. Det betyr ikke alltid at innholdet er digitalisert eller fritt tilgjengelig.</p><div className="side-rule"/><div className="eyebrow">EN ANNEN SKUFF</div><div className="drawers">{drawers.slice(1,5).map((d,i)=><button key={d.q} onClick={()=>openDrawer(d)}><span className="drawer-number">0{i+1}</span><span><b>{d.label}</b><small>{d.year||'Ulike år'} · {d.note}</small></span></button>)}</div></aside>
 <section className="results" aria-label="Søkeresultater"><div className="results-head"><div className="eyebrow">PÅ ARKIVBORDET</div><h2>{text||'Ditt neste funn'}</h2><p aria-live="polite">{loading?'Leter etter spor i arkivene …':`${shown.length} viste funn${total?' · '+total.toLocaleString('nb-NO')+' katalogtreff':''}`}</p></div>
 {(source==='all'||source==='dm')&&<div className="source-note"><Box size={20}/><div><b>En skuff til hos DigitaltMuseum</b><span>{data.find(s=>s.source==='dm')?.error||data.find(s=>s.source==='dm')?.notice||'Museumsgjenstander og fotografier i originalkatalogen.'}</span></div><a href={links[1].href} target="_blank" rel="noreferrer">Søk hos museene <ExternalLink size={14}/></a></div>}
 {!loading&&data.filter(s=>s.error&&s.source!=='dm').map(s=><div className="notice" key={s.source} role="status">{s.error} <a href={links.find(l=>l.id===s.source)?.href} target="_blank" rel="noreferrer">Åpne kildesøk</a></div>)}{error&&<div className="notice" role="alert">{error} <button onClick={()=>run()}>Prøv igjen</button></div>}
 {loading?<div className="loading"><LoaderCircle className="spin"/><p>Vi trekker ut skuffene …</p></div>:<><div className="cards">{shown.map((item,index)=>{const Icon=iconFor(item.kind);return <button className="card" key={item.source+item.id} onClick={()=>setSelected(item)}><div className={'card-visual '+(item.kind==='Lyd'?'sound':item.kind==='Aviser'?'news':'')}><span className="catalog-label">{item.source.toUpperCase()} / {String(search.page*24+index+1).padStart(3,'0')}</span>{item.image?<img src={item.image} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/>:<div className="type-display"><Icon size={43} strokeWidth={1}/><span>{item.kind}</span></div>}<span className="date-label">{item.year||'Udatert'}</span></div><div className="card-body"><div className="card-source">{sources[item.source]}</div><h3>{item.title}</h3><p className="creator">{item.creator||item.description||'Utforsk originalposten'}</p><span className={'access '+(item.open?'available':'')}>{item.access}</span><span className="card-action">Se funnet <ExternalLink size={14}/></span></div></button>})}</div>{!shown.length&&<div className="empty"><Archive size={35}/><h3>{kind==='objects'?'Gjenstandene finner du hos museene':'Ingen funn i denne skuffen'}</h3><p>{kind==='objects'?'Åpne DigitaltMuseum med søket ditt. Direkte museumssøk trenger API-tilgang.':'Prøv et annet søkeord, fjern årstallet eller velg alle katalogfunn.'}</p><div className="source-links">{links.filter(l=>source==='all'||l.id===source).map(l=><a key={l.id} href={l.href} target="_blank" rel="noreferrer">Søk hos {sources[l.id]} <ExternalLink size={14}/></a>)}</div></div>}{(items.length>0||search.page>0)&&<div className="pagination"><button disabled={search.page===0} onClick={()=>setSearch({...search,page:search.page-1})}>Forrige side</button><span>Side {search.page+1}</span><button disabled={!data.some(s=>s.total>(search.page+1)*12)||search.page>=49} onClick={()=>setSearch({...search,page:search.page+1})}>Neste side</button></div>}</>}
 </section></div><footer><span>Historieloftet <span className="muted">/ Fortiden er nærmere enn du tror.</span></span><button onClick={()=>setAbout(true)}>Kilder, tilgang og rettigheter</button></footer></main>
 <dialog aria-label="Arkivfunn" ref={dialog} onClose={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="dialog-content">{selected&&<><button className="close" onClick={()=>setSelected(null)} aria-label="Lukk funnet"><X/></button><div className="eyebrow">{sources[selected.source]} · {selected.kind}</div><h2>{selected.title}</h2><p>{[selected.creator,selected.year].filter(Boolean).join(' · ')}</p>{selected.image&&<img className="detail-image" src={selected.image} alt={selected.title}/>}<p className="description">{selected.description}</p><div className="detail-access"><b>{checking?'Sjekker tilgang hos kilden …':detail?.access||selected.access}</b><p>{detail?.error||((detail?.open??selected.open)?'Kilden oppgir tilgjengelig digitalt materiale. Åpne originalen for å lese, se eller lytte.':'Katalogen kan søkes selv om innholdet krever innlogging, lån, opphold i Norge eller besøk på biblioteket.')}</p></div>{detail?.audio&&<audio controls preload="none" src={detail.audio}>Nettleseren støtter ikke lydavspilling.</audio>}<h3>Rettigheter</h3><p className="rights">{detail?.rights||selected.rights}</p><p className="small">Tilgang til innhold er ikke det samme som tillatelse til gjenbruk. Kontroller kreditering og vilkår hos kilden før du deler eller publiserer materiale.</p><a className="primary-link" href={selected.url} target="_blank" rel="noreferrer">{selected.kind==='Lyd'?'Åpne lyd hos kilden':'Åpne originalen'} <ExternalLink size={17}/></a></>}</div></dialog>
 <dialog aria-label="Kilder og rettigheter" ref={aboutDialog} onClose={()=>setAbout(false)}><div className="dialog-content"><button className="close" onClick={()=>setAbout(false)} aria-label="Lukk kildeinformasjon"><X/></button><div className="eyebrow">OM LOFTET</div><h2>Tre dører til fortiden.</h2><p>Historieloftet søker i originalkataloger. Søkeord behandles som fritekst, og årstall som et eget filter. Et årstall kan beskrive utgivelse eller katalogens datering, ikke nødvendigvis motivet.</p><h3>Nasjonalbiblioteket</h3><p>Bøker, aviser, bilder og musikk. «Fri nettilgang» krever at katalogen oppgir digitalt materiale, full visning og tilgang overalt. Andre funn kan kreve norsk IP-adresse, innlogging eller bibliotekbesøk.</p><a href="https://www.nb.no/tilgang/rettigheter/" target="_blank" rel="noreferrer">Les om Nasjonalbibliotekets tilgang</a><h3>DigitaltMuseum</h3><p>Museumsgjenstander og fotografier. Åpnes med søkeord og årstall hos DigitaltMuseum inntil egen API-nøkkel er satt opp. Årstallet i denne søkelenken er fritekst.</p><a href="https://store-search.dimu.org/docs" target="_blank" rel="noreferrer">DigitaltMuseums dokumentasjon</a><h3>Internet Archive</h3><p>Bøker, bilder og lyd. Tilgang sjekkes når du åpner et funn; enkelte bøker krever lån. Lyd spilles her bare når katalogen oppgir en åpen lisens og en tilgjengelig MP3-fil.</p><a href="https://archive.org/developers/" target="_blank" rel="noreferrer">Internet Archives dokumentasjon</a><h3>Et funn er ikke en gjenbrukstillatelse</h3><p>Forhåndsvisninger fra Nasjonalbiblioteket vises bare for materiale katalogen merker som public domain med fri nettilgang. Øvrig innhold åpnes hos kilden. Rettigheter og tilgang kan endres.</p><p className="small">Treff blandes fra de tilkoblede kildene. Tilgangsfilteret gjelder de viste treffene; katalogtallet viser søkets total før dette filteret. Aviser søkes i Nasjonalbiblioteket, gjenstander hos DigitaltMuseum. Tilfeldig skuff velger mellom seks søkespor.</p></div></dialog></>;
}


