'use client';
import {useEffect,useRef,useState} from 'react';
import {ChevronLeft,ChevronRight,X,ZoomIn,ZoomOut,Maximize,Minimize,RotateCcw,ExternalLink,LoaderCircle} from 'lucide-react';
import PeriodPicker from './period-picker';
import {periodLabel} from '../lib/period';
import type {Fact} from '../lib/photo-details';
import type {RecordItem} from '../lib/archive';
type Page={url:string;large:string;label:string;width?:number;height?:number};
type Detail={recordKey?:string;facts?:Fact[];item?:RecordItem;pages?:Page[];audio?:string;embed?:string;access?:string;open?:boolean;rights?:string;error?:string};
const sourceName=(s:string)=>s==='nb'?'Nasjonalbiblioteket':s==='ia'?'Internet Archive':'DigitaltMuseum';
export function actionLabel(item:RecordItem){
 if(item.digital===false)return 'Se katalogpost';
 if(item.kind==='Bilder'&&(item.image||item.source==='ia'))return 'Se stort bilde';
 if(item.source==='nb'&&item.inlineReadable&&['Bøker','Aviser'].includes(item.kind))return 'Les her';
 if(item.kind==='Lyd')return 'Åpne lydopptak';
 if(['Bøker','Aviser'].includes(item.kind))return item.source==='nb'?'Les hos Nasjonalbiblioteket':'Åpne bok';
 return 'Se funnet';
}
export default function ArchiveViewer({item:original,onClose,onPrevious,onNext,photoIndex=-1,photoCount=0,morePhotos=false,fetchingPhotos=false,galleryError='',period='',periodExpanded=false,onPeriodChange}:{periodExpanded?:boolean;morePhotos?:boolean;fetchingPhotos?:boolean;galleryError?:string;period?:string;onPeriodChange?:(value:string)=>void;item:RecordItem;onClose:()=>void;onPrevious?:()=>void;onNext?:()=>void;photoIndex?:number;photoCount?:number}){
 const dialog=useRef<HTMLDialogElement>(null),stage=useRef<HTMLDivElement>(null),shell=useRef<HTMLDivElement>(null),viewport=useRef<HTMLDivElement>(null),audio=useRef<HTMLAudioElement>(null);
 const [loadedDetail,setDetail]=useState<Detail>({}),[loading,setLoading]=useState(true),[attempt,setAttempt]=useState(0),[page,setPage]=useState(0),[zoom,setZoom]=useState(1),[full,setFull]=useState(false),[expanded,setExpanded]=useState(false),[imageError,setImageError]=useState(false),[imageLoading,setImageLoading]=useState(true),[dimensions,setDimensions]=useState({width:1,height:1}),[frame,setFrame]=useState({width:800,height:600}),[audioError,setAudioError]=useState(false);
 const drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 const recordKey=original.source+':'+original.id,detail=loadedDetail.recordKey===recordKey?loadedDetail:{};
 const item=detail.item?{...detail.item,creator:detail.item.creator||original.creator}:original,pages=detail.pages||[],current=pages[page];
 const rich=!!(original.kind==='Bilder'||original.image||pages.length||detail.embed||loading&&original.inlineReadable);
 useEffect(()=>{dialog.current?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[]);
 useEffect(()=>{const c=new AbortController();setLoading(true);setDetail({});setPage(0);setZoom(1);setDimensions({width:1,height:1});setImageError(false);setImageLoading(true);setAudioError(false);drag.current=null;const route=original.source==='nb'?'item':original.source==='ia'?'access':null;
 if(!route){setDetail({recordKey});setLoading(false);return}
 fetch('/api/'+route+'?id='+encodeURIComponent(original.id),{signal:c.signal}).then(r=>r.json()).then(d=>{if(!c.signal.aborted)setDetail({...d as Detail,recordKey})}).catch(e=>{if(e.name!=='AbortError')setDetail({recordKey,error:'Visningen kunne ikke lastes. Prøv igjen.'})}).finally(()=>{if(!c.signal.aborted)setLoading(false)});return()=>c.abort()},[original.id,original.source,attempt]);
 useEffect(()=>{const fn=()=>{setFull(!!document.fullscreenElement);if(!document.fullscreenElement)setExpanded(false)};document.addEventListener('fullscreenchange',fn);return()=>document.removeEventListener('fullscreenchange',fn)},[]);
 useEffect(()=>{const node=viewport.current;if(!node)return;const o=new ResizeObserver(([e])=>setFrame({width:e.contentRect.width,height:e.contentRect.height}));o.observe(node);return()=>o.disconnect()},[rich,loading,detail]);
 useEffect(()=>{setZoom(1);setImageError(false);const img=viewport.current?.querySelector('img');setImageLoading(!(img?.complete&&img.naturalWidth>0));if(current)setDimensions({width:current.width||1,height:current.height||1});viewport.current?.scrollTo(0,0)},[page,current?.url]);
 const toggleFull=async()=>{if(document.fullscreenElement){await document.exitFullscreen();setExpanded(false);return}if(expanded){setExpanded(false);return}setExpanded(true);try{await shell.current?.requestFullscreen?.()}catch{/* Keep the full-window viewer when browser fullscreen is unavailable. */}};
 const exit=async()=>{if(document.fullscreenElement)try{await document.exitFullscreen()}catch{}onClose()};
 const w=current?.width||dimensions.width,h=current?.height||dimensions.height,fit=Math.min(Math.max(100,frame.width-32)/w,Math.max(100,frame.height-32)/h);
 const displayAccess=detail.access||item.access;
 const externalLabel=item.digital===false?'Se katalogpost hos '+sourceName(item.source):['Bøker','Aviser'].includes(item.kind)?'Les hos '+sourceName(item.source):item.kind==='Lyd'?'Lytt hos '+sourceName(item.source):'Se hos '+sourceName(item.source);
 const gallery=original.kind==='Bilder'&&photoIndex>=0?<nav className="photo-navigation" aria-label="Bla mellom bilder i søkeresultatet"><button disabled={!onPrevious} onClick={onPrevious} aria-label="Forrige bilde"><ChevronLeft size={23}/><span>Bilde</span></button><span aria-live="polite">Bilde {photoIndex+1}{morePhotos?' · ':' av '}{photoCount}{morePhotos?' lastet inn':''}<small>{fetchingPhotos?'Henter flere bilder …':galleryError?'Kunne ikke hente flere. Trykk Neste for å prøve igjen.':morePhotos?'Neste henter flere ved behov':'Slutten av søkeresultatet'}</small></span><button disabled={!onNext||fetchingPhotos} onClick={onNext} aria-label="Neste bilde"><ChevronRight size={23}/><span>Bilde</span></button></nav>:null;
 return <dialog onKeyDown={e=>{if(original.kind!=='Bilder'||e.altKey||e.ctrlKey||e.metaKey||e.shiftKey||(e.target as HTMLElement).closest('input,select,textarea,[contenteditable="true"]'))return;const move=e.key==='ArrowLeft'?onPrevious:e.key==='ArrowRight'?onNext:undefined;if(move){e.preventDefault();move()}}} ref={dialog} aria-label={item.title} className={'archive-dialog '+(rich?'has-media ':'')+(expanded?'expanded':'')} onCancel={e=>{e.preventDefault();void exit()}} onClose={onClose} onClick={e=>{if(e.target===e.currentTarget)void exit()}}>
 <div className="viewer-shell" ref={shell}><div className="viewer-header"><span>{sourceName(item.source)} · {item.kind}</span><button onClick={()=>void exit()} aria-label="Lukk visningen"><X size={22}/></button></div>
 {!rich&&gallery}<div className="viewer-layout">{rich&&<div className="media-stage" ref={stage}>
 {gallery}{detail.embed?<><div className="viewer-tools"><span>{item.kind==='Bilder'?'Bildevisning':'Les her'} · Internet Archive</span><button onClick={()=>void toggleFull()}><Maximize size={17}/> Fullskjerm</button></div><iframe title={(item.kind==='Bilder'?'Se ':'Les ')+item.title} src={detail.embed} allowFullScreen className="book-frame"/><p className="embed-help">Hvis visningen ikke åpnes: <a href={item.url} target="_blank" rel="noreferrer">{item.kind==='Bilder'?'Se bildet hos Internet Archive':'Les hos Internet Archive'}</a></p></>:<>
 <div className="viewer-tools"><button disabled={!current||zoom<=1} onClick={()=>setZoom(z=>Math.max(1,z-.5))} aria-label="Zoom ut"><ZoomOut size={19}/></button><output aria-label="Zoomnivå">{Math.round(zoom*100)} %</output><button disabled={!current||zoom>=4} onClick={()=>setZoom(z=>Math.min(4,z+.5))} aria-label="Zoom inn"><ZoomIn size={19}/></button><button disabled={!current} onClick={()=>{setZoom(1);viewport.current?.scrollTo(0,0)}}><RotateCcw size={16}/> Tilpass</button><button className="fullscreen-button" onClick={()=>void toggleFull()}>{full||expanded?<Minimize size={17}/>:<Maximize size={17}/>} {full||expanded?'Avslutt fullskjerm':'Fullskjerm'}</button></div>
 <div ref={viewport} className={'image-viewport '+(zoom>1?'can-pan':'')} tabIndex={0} aria-label="Bildevisning. Bruk zoomknappene og dra bildet eller rull for å flytte det." onPointerDown={e=>{if(zoom<=1||!viewport.current)return;drag.current={x:e.clientX,y:e.clientY,left:viewport.current.scrollLeft,top:viewport.current.scrollTop};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{const d=drag.current;if(!d||!viewport.current)return;viewport.current.scrollLeft=d.left-e.clientX+d.x;viewport.current.scrollTop=d.top-e.clientY+d.y}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 {loading?<div className="media-status" role="status"><LoaderCircle className="spin"/><p>Henter stor visning …</p></div>:current&&!imageError?<div className="image-canvas" style={{width:Math.max(frame.width,w*fit*zoom+32),height:Math.max(frame.height,h*fit*zoom+32)}}><img key={current.url} draggable={false} src={zoom>1.5?current.large:current.url} alt={item.title+(pages.length>1?' – side '+(page+1):'')} style={{width:w*fit*zoom,height:h*fit*zoom}} onLoad={e=>{setDimensions({width:e.currentTarget.naturalWidth,height:e.currentTarget.naturalHeight});setImageLoading(false)}} onError={()=>{setImageError(true);setImageLoading(false)}}/>{imageLoading&&<span className="image-progress" role="status">Laster bilde …</span>}</div>:<div className="media-status"><p>{detail.error||'Bildet kunne ikke vises her.'}</p><button onClick={()=>{setAttempt(a=>a+1);setImageError(false)}}>Prøv igjen</button><a href={item.url} target="_blank" rel="noreferrer">{externalLabel}</a></div>}
 </div><div className="page-controls">{pages.length>1?<><button aria-label="Forrige side" title="Forrige side" disabled={page===0} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={24}/><span>Side</span></button><label>Side <select aria-label="Velg side" value={page} onChange={e=>setPage(Number(e.target.value))}>{pages.map((p,i)=><option value={i} key={i}>{i+1}{p.label&&p.label!==String(i+1)?' · '+p.label:''}</option>)}</select> av {pages.length}</label><button aria-label="Neste side" title="Neste side" disabled={page===pages.length-1} onClick={()=>setPage(p=>p+1)}><ChevronRight size={24}/><span>Side</span></button></>:<span>{current?.width&&current?.height?`${current.width.toLocaleString('nb-NO')} × ${current.height.toLocaleString('nb-NO')} piksler i originalen`:'Stor bildevisning'}{zoom>1?' · Dra for å flytte bildet':''}</span>}</div></>}
 </div>}
 <div className="item-info">{onPeriodChange&&<details className="period-details" open={periodExpanded||undefined}><summary>Filtrer på tid · {periodLabel(period)}</summary><PeriodPicker value={period} onChange={onPeriodChange}/></details>}<div className="eyebrow">{item.kind} {item.year&&'· '+item.year}</div><h2>{item.title}</h2>{item.creator&&<p className="item-creator">{item.creator}</p>}<p className="small description">{item.description}</p>
 {item.kind==='Bilder'&&<section className="photo-information" aria-label="Bildeopplysninger"><h3>Om bildet</h3>{loading?<p role="status">Henter opplysninger fra arkivet …</p>:detail.facts?.length?<dl>{detail.facts.map(f=><div key={f.label}><dt>{f.label}</dt><dd>{f.value}</dd></div>)}</dl>:<p>{detail.error?'Bildeopplysningene kunne ikke hentes.':'Arkivet oppgir ikke flere bildeopplysninger.'}</p>}<p className="small">Opplysninger fra {sourceName(item.source)}. Datering kan være omtrentlig.</p></section>}
 <div className="detail-access"><b>{loading&&!rich?'Sjekker tilgang …':displayAccess}</b>{item.accessGroup==='norway'?<p>Kan leses hos Nasjonalbiblioteket fra norsk IP-adresse.</p>:item.accessGroup==='offline'?<p>Dette er en katalogpost. Digitalt innhold er ikke tilgjengelig.</p>:item.accessGroup==='restricted'||displayAccess.includes('lån')?<p>Kilden håndterer nødvendig innlogging, lån eller bibliotektilgang.</p>:!rich&&!detail.audio&&!loading?<p>{detail.error||'Bruk kildens visning for å åpne innholdet.'}</p>:null}</div>
 {detail.audio&&<><button className="play-button" onClick={()=>void audio.current?.play().catch(()=>setAudioError(true))}>Spill av</button><audio ref={audio} controls preload="none" src={detail.audio} onError={()=>setAudioError(true)}/>{audioError&&<p role="status">Lyden kunne ikke spilles. Bruk lenken til kilden.</p>}</>}
 {!rich&&detail.error&&<button onClick={()=>setAttempt(a=>a+1)}>Prøv tilgangssjekken igjen</button>}
 <p className="rights-line">{item.licenseUrl?<a href={item.licenseUrl} target="_blank" rel="noreferrer">{item.rights}</a>:item.publicDomain?'Public domain':detail.rights||item.rights}</p>
 {item.licenseUrl&&<p className="small">Kilde: <a href={item.url} target="_blank" rel="noreferrer">Nasjonalbiblioteket</a>. Skannene vises uendret.{item.nonCommercial?' Kun ikke-kommersiell bruk.':''}</p>}
 <details className="rights-details"><summary>Om rettigheter</summary><p>{item.publicDomain?'Kilden merker materialet som public domain. Oppgi gjerne fotograf eller opphavsperson og kilde ved gjenbruk.':item.accessGroup==='norway'?'Bokhylla-avtalen gir lesetilgang hos Nasjonalbiblioteket. NBs leser blokkerer innebygging på dette nettstedet.':item.licenseUrl?'Oppgi tittel, opphavsperson der denne er kjent, kilde og lisens ved gjenbruk. Følg lisensvilkårene som er lenket her.':'Tilgang og gjenbruksrettigheter er ulike ting. Se lisensen hos kilden før viderepublisering.'}</p><a href={item.licenseUrl||(item.source==='nb'?'https://www.nb.no/tilgang/lisens/':item.url)} target="_blank" rel="noreferrer">Se kildens vilkår</a></details>
 <a className={rich||detail.audio?'source-secondary':'primary-link'} href={item.url} target="_blank" rel="noreferrer">{rich?'Original og kildeopplysninger':externalLabel}<ExternalLink size={16}/></a>
 </div></div></div></dialog>;
}

