'use client';
import {Fragment,useState} from 'react';
import {Archive,ArrowLeft,Camera} from 'lucide-react';
import ArchiveViewer from '../../../components/archive-viewer';
import {fredrikstadPilot as pilot,filterPilot,groupFor,type PilotFilters} from '../../../lib/pilot';
const initial:PilotFilters={method:'visual',group:'',place:'',year:'',status:'',order:'oldest'};
export default function Pilot(){
 const [filters,setFilters]=useState(initial),[selectedId,setSelectedId]=useState<string|null>(null);
 const update=(patch:Partial<PilotFilters>)=>{setSelectedId(null);setFilters(f=>({...f,...patch}))};
 const shown=filterPilot(pilot.items,filters),index=shown.findIndex(x=>x.id===selectedId),selected=shown[index];
 const groups=[...new Set(pilot.items.map(x=>groupFor(x,filters.method)))].sort((a,b)=>a.localeCompare(b,'nb'));
 const places=[...new Set(pilot.items.map(x=>x.subgroup))].sort((a,b)=>a.localeCompare(b,'nb'));
 const years=[...new Set(pilot.items.map(x=>x.sortYear))].sort();
 const groupCount=(g:string)=>filterPilot(pilot.items,{...filters,group:g}).length;
 return <><header className="top"><a href="/" className="brand"><Archive size={24}/><span>Historieloftet<span className="brand-small">ET STED FOR GAMLE SPOR</span></span></a><a href="/">Til arkivet</a></header>
 <main className="pilot-main"><a className="pilot-back" href="/"><ArrowLeft size={16}/> Tilbake til alle arkivtreff</a><a className="pilot-companion" href="/pilot">Se Sarpsborg-piloten</a><div className="eyebrow">PILOTSAMLING · FREDRIKSTAD</div><h1>Fredrikstad <em>1920–1929</em></h1><p className="pilot-lead">200 nye bilder. Utforsk motivene, sammenlign grupperingen og se hvorfor bildene er samlet.</p>
 <div className="pilot-stats"><span><b>200</b> faste bilder</span><span><b>{groups.length}</b> motivgrupper i valgt visning</span><span><b>{pilot.items.filter(x=>x.needsReview).length}</b> trenger ekstra kontroll</span><span><b>0</b> bekreftede GPS-punkter</span></div>
 <details className="pilot-method"><summary>Hva er testet, og hvordan ble bildene valgt?</summary><p>{pilot.selection}</p><p>Her betyr Fredrikstad arkivets geografiske registrering, inkludert blant annet Onsøy, Glemmen, Rolvsøy og Hankø. Dateringen er arkivets; «1920» kan være omtrentlig. År uten treff i utvalget vises ikke i årfilteret.</p><p>{pilot.review}</p><p>Visuell gjennomgang er forslag fra bildeanalyse i denne samtalen, ikke menneskelig godkjenning. Baksider av fotografier ble holdt utenfor dette utvalget. Arkivvisningen bruker enkle regler på titler og stedsopplysninger. Modellene er ikke sammenlignet, og det er ikke kjørt egen OCR eller automatisk identifisering av konkrete steder.</p><p>{pilot.gpsStatus} Bok- og aviskoblinger er ennå ikke undersøkt.</p><p>Hentet {new Date(pilot.fetchedAt).toLocaleDateString('nb-NO')} fra {pilot.sourceTotal} åpne NB-treff. Opplysninger og grupper er lagret som en fast, versjonert samling.</p></details>
 <section className="pilot-filters" aria-label="Filtrer pilotsamlingen">
 <label>Gruppering<select value={filters.method} onChange={e=>update({method:e.target.value,group:''})}><option value="visual">Visuell gjennomgang + arkiv</option><option value="metadata">Bare arkivopplysninger</option></select></label>
 <label>Sted / sammenheng<select value={filters.place} onChange={e=>update({place:e.target.value})}><option value="">Alle steder og sammenhenger</option>{places.map(p=><option key={p}>{p}</option>)}</select></label>
 <label>År<select value={filters.year} onChange={e=>update({year:e.target.value})}><option value="">Hele 1920–1929</option>{years.map(y=><option key={y}>{y}</option>)}</select></label>
 <label>Analysestatus<select value={filters.status} onChange={e=>update({status:e.target.value})}><option value="">Alle vurderinger</option><option value="uncertain">Trenger ekstra kontroll</option><option value="reviewed">Visuelt gjennomgått</option><option value="pending">Ikke gjennomgått</option></select></label>
 <label>År innen gruppen<select value={filters.order} onChange={e=>update({order:e.target.value})}><option value="oldest">Eldste først</option><option value="newest">Nyeste først</option></select></label>
 <button className="pilot-reset" onClick={()=>{setSelectedId(null);setFilters(initial)}}>Nullstill filtre</button>
 </section>
 <nav className="pilot-groups" aria-label="Motivgrupper"><button aria-pressed={!filters.group} onClick={()=>update({group:''})}>Alle grupper <span>{filterPilot(pilot.items,{...filters,group:''}).length}</span></button>{groups.map(g=><button key={g} aria-pressed={filters.group===g} onClick={()=>update({group:g})}>{g} <span>{groupCount(g)}</span></button>)}</nav>
 <p className="pilot-result-count" role="status">{shown.length} av 200 bilder · Pilene følger disse filtrene og rekkefølgen.</p>
 <section className="cards pilot-cards" aria-label="Bilder i pilotsamlingen">{shown.map((item,i)=>{const group=groupFor(item,filters.method);return <Fragment key={item.id}>{(i===0||groupFor(shown[i-1],filters.method)!==group)&&<h2 className="pilot-group-heading">{group}<small>{shown.filter(x=>groupFor(x,filters.method)===group).length} bilder</small></h2>}{(i===0||groupFor(shown[i-1],filters.method)!==group||shown[i-1].subgroup!==item.subgroup)&&<h3 className="place-heading">{item.subgroup}</h3>}<button className="card" onClick={()=>setSelectedId(item.id)}><div className="card-visual"><span className="catalog-label">PILOT / {String(item.pilotNumber).padStart(3,'0')}</span><img src={item.image} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display='none'}}/><span className="date-label">{item.year}</span></div><div className="card-body"><div className="card-source">Nasjonalbiblioteket</div><h3>{item.title}</h3><p className="creator">{item.creator}</p><span className={'pilot-status '+(item.needsReview?'uncertain':'')}>{item.needsReview?'Trenger ekstra kontroll':'Visuelt vurdert · forslag'}</span><span className="card-action">Se bilde og begrunnelse <Camera size={16}/></span></div></button></Fragment>})}</section>
 {!shown.length&&<div className="empty"><h2>Ingen bilder med disse filtrene</h2><p>Utvid filtrene eller velg en annen motivgruppe.</p><button onClick={()=>{setSelectedId(null);setFilters(initial)}}>Vis alle 200</button></div>}
 <footer>Fast pilotutvalg · Originalene ligger hos Nasjonalbiblioteket.</footer></main>
 {selected&&<ArchiveViewer item={selected} photoIndex={index} photoCount={shown.length} onClose={()=>setSelectedId(null)} onPrevious={index>0?()=>setSelectedId(shown[index-1].id):undefined} onNext={index<shown.length-1?()=>setSelectedId(shown[index+1].id):undefined} pilotInfo={<section className="pilot-analysis" aria-label="Pilotvurdering"><div className="eyebrow">PILOT {selected.pilotNumber} / 200</div><h3>{groupFor(selected,filters.method)}</h3><p><b>Visuelt forslag:</b> {selected.group}</p><p>{selected.visualNote}</p><p><b>Bare arkivopplysninger:</b> {selected.metadataGroup}</p><p><b>Sted / sammenheng:</b> {selected.subgroup}</p><p className="small">{selected.groupBasis}</p>{selected.needsReview&&<p className="pilot-warning">Uklart eller detaljfattig bilde. Trenger ekstra kontroll.</p>}<details><summary>Stedfesting og GPS</summary><p>{selected.location.label}</p><p>{selected.location.status}. Ingen koordinater eller nøyaktig fotografposisjon er fastslått.</p></details></section>}/>}
 </>;
}
