import {nbFilters,iaAccessQuery,type AccessFilter} from '../../../lib/search-filters';
import {nbItem,iaItem,json,literal,str} from '../../../lib/archive';
export async function GET(request:Request){
 const p=new URL(request.url).searchParams,q=(p.get('q')||'').trim().slice(0,150),year=p.get('year')||'',kind=p.get('kind')||'all',source=p.get('source')||'all',page=Math.min(49,Math.max(0,Number(p.get('page'))||0));
 if(!q&&!year)return Response.json({error:'Skriv et sted, tema eller årstall.'},{status:400});
 if(year&&!/^\d{4}$/.test(year))return Response.json({error:'Bruk et firesifret årstall.'},{status:400});
 const access=(p.get('access')||'all') as AccessFilter, includeCatalog=p.get('catalog')==='true';
 if(!['all','available','open','norway','restricted','offline'].includes(access))return Response.json({error:'Ugyldig tilgangsfilter.'},{status:400});
 const jobs:Array<Promise<any>>=[];
 if(source==='all'||source==='nb')jobs.push((async()=>{if(kind==='objects')return {source:'nb',items:[],total:0};const u=new URL('https://api.nb.no/catalog/v1/items');u.searchParams.set('q',q?literal(q):'*');u.searchParams.set('size','12');u.searchParams.set('page',String(page)); nbFilters(access,includeCatalog).forEach(f=>u.searchParams.append('filter',f)); if(year)u.searchParams.append('filter','year:'+year);const media:any={photos:'bilder',news:'aviser',books:'bøker',audio:'musikk'};if(media[kind])u.searchParams.append('filter','mediatype:'+media[kind]);const d=await json(u.href);return {source:'nb',items:(d._embedded?.items||[]).map(nbItem),total:d.page?.totalElements||0};})().catch(()=>({source:'nb',items:[],error:'Nasjonalbiblioteket svarte ikke. Prøv igjen eller søk hos kilden.'})));
 if(source==='all'||source==='ia')jobs.push((async()=>{const accessQuery=iaAccessQuery(access);if(kind==='objects'||kind==='news'||accessQuery===null)return {source:'ia',items:[],total:0};const u=new URL('https://archive.org/advancedsearch.php');const media:any={photos:'image',books:'texts',audio:'audio'};let query=q?literal(q):'*:*';query+=' AND '+(media[kind]?'mediatype:'+media[kind]:'mediatype:(texts OR audio OR image)');if(year)query+=' AND year:'+year;query+=accessQuery;u.searchParams.set('q',query);u.searchParams.set('output','json');u.searchParams.set('rows','12');u.searchParams.set('page',String(page+1));['identifier','title','creator','date','year','mediatype','description','licenseurl','rights','access-restricted-item'].forEach(f=>u.searchParams.append('fl[]',f));const d=await json(u.href);if(!d.response)throw Error();return {source:'ia',items:d.response.docs.map(iaItem),total:d.response.numFound,notice:(access==='open'||access==='available')?'Internet Archive: lånebegrensede poster er filtrert bort. Filtilgang sjekkes når du åpner et funn.':undefined};})().catch(()=>({source:'ia',items:[],error:'Internet Archive svarte ikke. Prøv igjen eller søk hos kilden.'})));
 // Ordinary DigitaltMuseum API use requires the owner's key; never ship the test key.
 if(source==='all'||source==='dm')jobs.push((async()=>{if(access!=='all')return {source:'dm',items:[],notice:'DigitaltMuseum har ikke tilsvarende tilgangsfilter her. Du kan søke hos museene.'};const key=process.env.DIMU_API_KEY;if(!key)return {source:'dm',items:[],notice:'DigitaltMuseum åpnes hos kilden. Direkte katalogsøk er ikke tilkoblet.'};const u=new URL('https://store-search.dimu.org/api/solr/select');u.searchParams.set('q',q?literal(q):'*:*');u.searchParams.set('wt','json');u.searchParams.set('rows','12');u.searchParams.set('start',String(page*12));u.searchParams.set('api.key',key);if(year)u.searchParams.append('fq','artifact.event.fromYear:'+year);if(kind==='photos')u.searchParams.append('fq','artifact.type:Photograph');else if(kind==='objects')u.searchParams.append('fq','artifact.type:Thing');else if(kind!=='all')return {source:'dm',items:[],total:0};const d=await json(u.href);if(!d.response)throw Error();return {source:'dm',total:d.response.numFound,items:d.response.docs.map((x:any)=>({id:str(x['artifact.uniqueId']),source:'dm',title:str(x['artifact.ingress.title'])||'Uten tittel',creator:str(x['artifact.ingress.producer']),year:str(x['artifact.ingress.production.fromYear']),kind:x['artifact.type']==='Photograph'?'Bilder':'Gjenstander',url:'https://digitaltmuseum.no/'+encodeURIComponent(str(x['artifact.uniqueId'])),access:'Katalogpost med kildevisning',open:false,rights:str(x['artifact.ingress.license'])||'Se rettigheter hos museet',description:str(x['artifact.ingress.production.place'])}))};})().catch(()=>({source:'dm',items:[],error:'DigitaltMuseum svarte ikke. Søk direkte hos kilden.'})));
 return Response.json({sources:await Promise.all(jobs)},{headers:{'Cache-Control':'private, max-age=120'}});
}
